### ISSUE TITLE
Last page of feed throws error

### ISSUE THREAD

**Issue by house92** [britishcycling-oa/opendata#4]
It seems that when your feed runs out of data to provide it throws an error like the example below rather than merely providing an empty array. Could you look into this please?

```
{
  'errors': [
    {
      'message': 'Internal Server Error',
      'code': 'GEN'
    }
  ]
}
```

**Comment by benjamindoe** [comment]
I've noticed that it's not just the last page but various others too depending on the date. Not sure what the pattern is though

https://api.letsride.co.uk/public/v1/rides?from=2018-06-11+01%3A02%3A10
https://api.letsride.co.uk/public/v1/rides?from=2018-02-12+14%3A47%3A28

**Comment by kent-gosweat** [comment]
Came across the same issue. Presuming it's relating to the lack of data?

Results are still being returned for 1970.

**Comment by sevenpointsix** [comment]
I believe that this has now been resolved (on our staging server) but this should be checked again post-launch @nickevansuk @house92 .

**Comment by sevenpointsix** [comment]
Do we have an update on this @nickevansuk @house92 ...? Thanks!

**Comment by house92** [comment]
@sevenpointsix It seems to still be an issue: http://api.letsride.co.uk/public/v1/rides?from=1970-01-01+01%3A13%3A19

**Comment by sevenpointsix** [comment]
@house92 Sorry, I've confused things there; these changes aren't live, just on staging. The staging URL for the API is http://lr-api.staging.phoenixdigital.agency/public/v1/rides . Could you possibly check this issue at that URL? cc. @nickevansuk

**Comment by nickevansuk** [comment]
Hi @sevenpointsix - if you put that URL in our new validator tool, you'll see all the errors there :)

https://data-model-validator-staging.herokuapp.com/rpde?url=http://lr-api.staging.phoenixdigital.agency/public/v1/rides

Best to keep working on this until the validator passes - hopefully more efficient than manual checking! (Can't tell you how relieved I am to have a validator at last!)

**Comment by GetTheData** [comment]
I'm still seeing this issue on live, see:

http://api.letsride.co.uk/public/v1/rides?afterTimestamp=1101&afterId=5590

**Comment by RickCrilly** [comment]
Hi,

Since the fix in #8 I have tested this with the validator and it is not passing. However, there is no longer an internal server error returned.

**Comment by domfennell** [comment]
Many thanks for sorting issue #8, @RickCrilly. Do you have a timeframe for addressing the errors & warnings thrown-up by the Validator?

**Comment by nickevansuk** [comment]
Just to give you a breakdown of the source of each of the errors in the validator, if helpful:

These two are quick to fix:
- `kind` can be updated to `Event`
- `url`s can be url encoded, so `"url": "https://media.letsride.co.uk/view/13462570c717276edddf28d1a0727d89/2018 LETS RIDE LONGBOX RGB LOGO KEYLINE.svg"` should be `"url": "https://media.letsride.co.uk/view/13462570c717276edddf28d1a0727d89/2018%20LETS%20RIDE%20LONGBOX%20RGB%20LOGO%20KEYLINE.svg"`

This one may not require any attention:
- `organizer` is currently included for cases where the ride is organised by a group, otherwise there is no obvious responsible party for the rides? Unless there is a clear organisation or person responsible for rides that are not part of a group, suggest this error is ignored in this context.

These can be ignored:
- Required field errors around `Place` `name`, `addressLocality`, `addressRegion`, `streetAddress` can be ignored as Let's Ride doesn't capture this data. For ad-hoc event locations, future versions of the modelling specification will likely loosen the requirements around these fields as they often prove problematic in this context.

**Comment by RickCrilly** [comment]
@domfennell Despite the issues appearing to be frustrating simple on the surface (thanks to @nickevansuk for helpfully pointing this out), I'm sorry, I can't give an accurate time frame for the fix. The best I can offer at this point is 'in the coming months'.  

Apologies for the inconvenience this is causing anyone.

**Comment by sevenpointsix** [comment]
@nickevansuk Are you able to confirm the URL at which you see these errors? For example, "kind", "organizer" and so on. I'm not seeing them here (https://data-model-validator-staging.herokuapp.com/rpde?url=https://api.letsride.co.uk/public/v1/rides) but I'm guessing there must be other pages of the feed that aren't valid?

**Comment by nickevansuk** [comment]
Sure see here: https://validator.openactive.io/?url=http%3A%2F%2Fapi.letsride.co.uk%2Fpublic%2Fv1%2Frides%3FafterTimestamp%3D1101%26afterId%3D5590&version=2.0

**Comment by sevenpointsix** [comment]
@nickevansuk I'm getting an application error from that URL (https://validator.openactive.io/?url=http%3A%2F%2Fapi.letsride.co.uk%2Fpublic%2Fv1%2Frides%3FafterTimestamp%3D1101%26afterId%3D5590&version=2.0). Am I doing something wrong?

**Comment by nickevansuk** [comment]
Closing as appears to have been resolved
